[package]
name = "mjava_scanner"
version = "0.1.0"
authors = ["huaiyugong <huaiyugong123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest=false

[dependencies]
